### ISSUE TITLE
Oh No, caff2onnx failed :( ,无其他任何提示

### ISSUE THREAD

**Issue by GreenValue** [Tencent/TNN#1005]
**1. 使用环境（environment）**
 - OS: turandotkay/tnn-convert Docker

  **2. 先将caffe 网络和模型转换为新版**
 - OS：bvlc/caffe:gpu
  ```
./upgrade_net_proto_text VGG_ILSVRC_19_layers_deploy.prototxt new.prototxt
./upgrade_net_proto_binary VGG_ILSVRC_19_layers.caffemodel new.caffemodel

 ```
  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（caffe converter failed）
 - original model： 
链接：https://pan.baidu.com/s/19FjYHSRNWJILGLobcf2WmQ 
提取码：abob 
复制这段内容后打开百度网盘手机App，操作更方便哦
 - 转换为新版 model：  
链接：https://pan.baidu.com/s/1ehmIDF8LPadIecZP3m762Q 
提取码：v8f3 
复制这段内容后打开百度网盘手机App，操作更方便哦

  **4. 日志（Log）**
 ```txt
root@202012:/usr/work/caffe_docker/cpy_data# tree -h
.
├── [548M]  new.caffemodel
├── [5.6K]  new.prototxt
├── [548M]  VGG_ILSVRC_19_layers.caffemodel
└── [5.6K]  VGG_ILSVRC_19_layers_deploy.prototxt


0 directories, 4 files
root@202012:/usr/work/caffe_docker/cpy_data# docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py caffe2tnn \
>     /workspace/new.prototxt \
>     /workspace/new.caffemodel \
>     -optimize \
>     -v v1.0 \
>     -align  \
>     -input_file /workspace/in.txt \
>     -ref_file /workspace/ref.txt

----------  convert model, please wait a moment ----------

Converter Caffe to ONNX Model

Oh No, caff2onnx failed :(

 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/16701660/120456920-9f64f000-c3c8-11eb-8d46-1f04274abc40.png)

**Comment by GreenValue** [comment]
拜求指教

**Comment by GreenValue** [comment]
上面的模型可能有些陈旧，所以
我用[官网](https://www.robots.ox.ac.uk/~vgg/research/very_deep/)上的VGG_ILSVRC_19_layers
http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_19_layers.caffemodel
https://gist.githubusercontent.com/ksimonyan/3785162f95cd2d5fee77/raw/f02f8769e64494bcd3d7e97d5d747ac275825721/VGG_ILSVRC_19_layers_deploy.prototxt

为了方便，我已分享到百度网盘：
链接: https://pan.baidu.com/s/1ho8GO-e1lRnmKmDj_bAvFA 提取码: gyzg 


- 进入docker

```
docker run --name tnn_conv --volume=$(pwd):/workspace -it tnn-convert:latest  /bin/bash
```

- docker中执行caffe2onnx，但报错了！

```
root@3fa818b26784:/opt/TNN/tools/caffe2onnx# python3 caffe2onnx.py /workspace/mzr_VGG_ILSVRC_19_layers_deploy.prototxt /workspace/mzrVGG_ILSVRC_19_layers.caffemodel -o ./test.onnx
2. 开始进行模型转换
convert layer: conv1_1
convert layer: relu1_1
convert layer: conv1_2
convert layer: relu1_2
convert layer: pool1
convert layer: conv2_1
convert layer: relu2_1
convert layer: conv2_2
convert layer: relu2_2
convert layer: pool2
convert layer: conv3_1
convert layer: relu3_1
convert layer: conv3_2
convert layer: relu3_2
convert layer: conv3_3
convert layer: relu3_3
convert layer: conv3_4
convert layer: relu3_4
convert layer: pool3
convert layer: conv4_1
convert layer: relu4_1
convert layer: conv4_2
convert layer: relu4_2
convert layer: conv4_3
convert layer: relu4_3
convert layer: conv4_4
convert layer: relu4_4
convert layer: pool4
convert layer: conv5_1
convert layer: relu5_1
convert layer: conv5_2
convert layer: relu5_2
convert layer: conv5_3
convert layer: relu5_3
convert layer: conv5_4
convert layer: relu5_4
convert layer: pool5
convert layer: fc6
Traceback (most recent call last):
  File "caffe2onnx.py", line 35, in <module>
    main(args)
  File "caffe2onnx.py", line 22, in main
    c2o = Caffe2Onnx(graph, params, onnx_name)
  File "/opt/TNN/tools/caffe2onnx/src/caffe2onnx.py", line 29, in __init__
    self.GenerateOnnxNodeList(LayerList)
  File "/opt/TNN/tools/caffe2onnx/src/caffe2onnx.py", line 732, in GenerateOnnxNodeList
    need_reshape = 0 if reshape_output_shape[0] == node_input_shape[0] else 1
TypeError: 'NoneType' object is not subscriptable

```
