### ISSUE TITLE
linux_native TNNTest 报错 Illegal instruction

### ISSUE THREAD

**Issue by likefxz2009** [Tencent/TNN#1188]
使用build_linux_native.sh编译出库和test，然后执行TNNTest报错Illegal instruction。
编译和执行在同样的环境下
系统版本
```
Linux build 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
```
gcc版本：
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
```
cmake版本
```
cmake version 3.7.2
```
如果用官方的docker镜像则不会出现这个问题

**Comment by likefxz2009** [comment]
cmake升级到3.20.5问题仍然存在

**Comment by seanxcwang** [comment]
你的芯片是什么型号，你可以用gdb跟一下，看具体是什么指令非法

**Comment by likefxz2009** [comment]
@seanxcwang 
cpuinfo:
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
stepping	: 9
microcode	: 0x16
cpu MHz		: 1600.000
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips	: 6385.16
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

gdb结果
```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./TNNTest...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/fangxz/TNN/scripts/build_linux_native/test/TNNTest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007ffff760e5f6 in tnn::X86Unary2LayerAcc::GetUnaryKernelName[abi:cxx11](tnn::LayerType, tnn::x86_isa_t) () from /home/fangxz/TNN/scripts/build_linux_native/libTNN.so.0
(gdb) bt
#0  0x00007ffff760e5f6 in tnn::X86Unary2LayerAcc::GetUnaryKernelName[abi:cxx11](tnn::LayerType, tnn::x86_isa_t) () from /home/fangxz/TNN/scripts/build_linux_native/libTNN.so.0
#1  0x00007ffff760ff15 in tnn::X86Unary2LayerAcc::RegisterUnary2Kernel(tnn::LayerType, tnn::x86_isa_t, void (*)(std::vector<int, std::allocator<int> >, float const*, float*, tnn::LayerParam*)) ()
   from /home/fangxz/TNN/scripts/build_linux_native/libTNN.so.0
#2  0x00007ffff72b8414 in _GLOBAL__sub_I_x86_abs_layer_acc.cc () from /home/fangxz/TNN/scripts/build_linux_native/libTNN.so.0
#3  0x00007ffff7de879a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe458, env=env@entry=0x7fffffffe468) at dl-init.c:72
#4  0x00007ffff7de88ab in call_init (env=0x7fffffffe468, argv=0x7fffffffe458, argc=1, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=0x7ffff7ffe170, argc=1, argv=0x7fffffffe458, env=0x7fffffffe468) at dl-init.c:120
#6  0x00007ffff7dd9c5a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in ?? ()
#8  0x00007fffffffe686 in ?? ()
#9  0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by seanxcwang** [comment]
display下具体的汇编指令

**Comment by likefxz2009** [comment]
应该是我的机器不支持avx2的原因，但是关闭CMake里面的-maxv2选项后，编译报错，因为有用到avx2指令的地方没有用宏来控制

**Comment by likefxz2009** [comment]
关闭-mavx2后，X86AVXGemmInt8Unit4x4这个函数里有用到avx2的指令，但是没有用ifdef _AVX2_来控制，所以编译报错，将相关指令注释后，重新编译通过，并且运行test也不会在出现之前的问题。
所以总的来说是我机器本身不支持avx2的问题，我编译的时候没有去看编译选项，不过这个X86AVXGemmInt8Unit4x4函数里面的问题建议处理一下

**Comment by powerpwang** [comment]
Fixed. #1213
