### ISSUE TITLE
在iOS端，打开GPU进行人脸推理，内存会一直涨。

### ISSUE THREAD

**Issue by haityang** [Tencent/TNN#1486]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: IOS
 - RunTime DEVICE: METAL

  **2. Github版本**
 - branch：tnn-v0.3.0-ios.zip
 - commit(optional):

  **3. 编译方式(compile method)**
XCode编译

  **4. 编译日志(build log)**
 ```txt

 ```

  **5. 详细描述bug 情况 (Describe the bug)**
使用人脸推理（version-slim-320_simplified），打开GPU的方式（TNN_NS::TNNComputeUnitsGPU），通过播放本地视频，拿到回调后进行推理，内存会一直涨，直到崩溃。下面是崩溃堆栈。如果改成cpu的方式（TNN_NS::TNNComputeUnitsCPU），则一切正常。

  **6. 运行日志（runtime log）**
 ```txt
Thread 14 Queue : com.demo.player.ai.loop (serial)
#0  0x00000001e7b30628 in _platform_memmove ()
#1  0x00000001012d0ca0 in tnn::MetalBlobConverterAcc::ConvertToMatCommon(tnn::Mat&, tnn::Blob*, void*, int) ()
#2  0x000000010132d578 in tnn::BlobConverter::ConvertToMat(tnn::Mat&, tnn::MatConvertParam, void*) ()
#3  0x00000001013be300 in tnn::Instance::GetOutputMat(std::__1::shared_ptr<tnn::Mat>&, tnn::MatConvertParam, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, tnn::DeviceType, tnn::MatType) ()
#4  0x000000010120a500 in tnn::TNNSDKSample::Predict(std::__1::shared_ptr<tnn::TNNSDKInput>, std::__1::shared_ptr<tnn::TNNSDKOutput>&) at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/IotTnn/IotTnn/AI/base/tnn_sdk_sample.cc:837
#5  0x00000001011f67c8 in -[UltraFace detectObject:imageSize:threshold:nms_threshold:useGPU:] at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/IotTnn/IotTnn/AI/UltraFace.mm:188
#6  0x00000001011f5810 in -[UltraFace detect:image:threshold:nms_threshold:useGPU:] at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/IotTnn/IotTnn/AI/UltraFace.mm:83
#7  0x00000001011f324c in -[ITnnManager detectFace:image:threshold:nms_threshold:useGPU:] at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/IotTnn/IotTnn/AI/ITnnManager.m:48
#8  0x0000000100d3f5a4 in -[AVPlayerSampleViewController detectWithType:image:targetObjects:] at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/AVPlayerSample/Classes/AVPlayerSampleViewController.m:156
#9  0x0000000100d3f3a0 in -[AVPlayerSampleViewController doDetectionWithPolicy:] at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/AVPlayerSample/Classes/AVPlayerSampleViewController.m:142
#10 0x0000000100d3f038 in __42-[AVPlayerSampleViewController onAiDetect]_block_invoke at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/AVPlayerSample/Classes/AVPlayerSampleViewController.m:106
#11 0x0000000100d3f240 in __48-[AVPlayerSampleViewController threadLoopBlock:]_block_invoke at /Users/xx/WS/AI/PlayerTnn/PlayerTnn/AVPlayerSample/Classes/AVPlayerSampleViewController.m:132
#12 0x00000001017480b4 in _dispatch_call_block_and_release ()
#13 0x0000000101749de0 in _dispatch_client_callout ()
#14 0x0000000101751ef0 in _dispatch_lane_serial_drain ()
#15 0x0000000101752d14 in _dispatch_lane_invoke ()
#16 0x000000010175fa50 in _dispatch_workloop_worker_thread ()
#17 0x00000001e7b367a4 in _pthread_wqthread ()
 ```

  **7. 截图（Screenshots）**
 ```txt

![Screen Shot 2021-12-20 at 9 06 57 PM](https://user-images.githubusercontent.com/184515/146771801-e9ee53cc-f0cf-412e-b42e-1369b4c5db05.png)

 ```

**Comment by xifengiOS** [comment]
找到demo中UIImage+util 类别，在图片处理方法中 释放cgimage对象。

**Comment by haityang** [comment]
是我在timer另起队列取pixbuf，未加autoreleasepool, 至使pixbuf没有及时释放造成的。
