### ISSUE TITLE
caffe2onnx PeRelu保存模型报错

### ISSUE THREAD

**Issue by YjDai** [Tencent/TNN#535]
模型存在问题,未保存成功: Nodes in a graph must be topologically sorted, however input '_slope' of node: 
input: "conv1/bn" input: "_slope" output: "relu1" name: "relu1" op_type: "PRelu"
 is not output of any previous nodes.

**Comment by 1627180283** [comment]
方便提供一下模型吗

**Comment by YjDai** [comment]
@1627180283 联系方式是啥

**Comment by 1627180283** [comment]
> @1627180283 联系方式是啥

1627180283 这个是我的  QQ

**Comment by liushuan** [comment]
带PRelu的模型目前可以转换成功 但是运行会报错：
Traceback (most recent call last):
  File "E:/dataset/safety_helmet_data/TNN-master/tools/caffe2onnx/caffe2onnx.py", line 134, in <module>
    main(args)
  File "E:/dataset/safety_helmet_data/TNN-master/tools/caffe2onnx/caffe2onnx.py", line 127, in main
    output = o_net_onnx.forward(data)
  File "E:/dataset/safety_helmet_data/TNN-master/tools/caffe2onnx/caffe2onnx.py", line 70, in forward
    output = self.onnx_session.run(self.output_name, input_feed=input_feed)
  File "C:\Users\lzhpc\AppData\Roaming\Python\Python37\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running PRelu node. Name:'' Status Message: C:\a\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:479 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 24 by 126

上面的24是 channels(C)  126是 Height(H), 感受是不是通道和宽高哪儿没有对应正确。
